### ISSUE TITLE
Tab pane, persistence of langauge: js error

### ISSUE THREAD

**Issue by deining** [google/docsy#1232]
As mentioned and discused in #1202, a regression was introduced with 10fae88de482d836f0c81437afad5674418a888d:
When persisting the language of a tab pane, the following error is now thrown in the browser's javascript console:

```
Uncaught TypeError: $(...).tab is not a function
    <anonymous> http://localhost:1313/js/tabpane-persist.js:7
    <anonymous> http://localhost:1313/js/tabpane-persist.js:6
```
